# Generated by Django 5.0.6 on 2024-06-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_v1", "0002_alter_cart_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="product",
        ),
        migrations.AddField(
            model_name="cart",
            name="product",
            field=models.ManyToManyField(
                null=True,
                related_name="cart_product",
                to="api_v1.product",
                verbose_name="Товар",
            ),
        ),
    ]
